// src/constants/strings.ts
export const STRINGS = {
  appTitle: 'Brandi\'s Job Tracker',
  loading: 'Loading...',
  save: 'Save',
  cancel: 'Cancel',
  noApplications: 'No job applications yet.',
  seeNotes: 'See notes',
  seeApplications: 'See Applications',
  homeBlurb: 'Keep your job search organized in one place. Track companies, manage applications, and save interview notes so you always know what comes next.',
  homeBlurb2Title: 'Stay organized during your job search',
  homeBlurb2: 'Use this app to keep track of where you applied, what stage each opportunity is in, and the notes you want to remember before your next interview.',
  manageCompanies: 'Manage Companies',
  trackApplications: 'Track Applications',
  notesTitle: 'Interview Notes',
  saveInterviewNotes: 'Save Interview Notes',
  buildMomentum: 'Reach the Next Level',
  buildMomentumBlurb: 'A consistent system makes it easier to follow up, prepare for interviews, and spot where your search is gaining traction. Don\'t let your next opportunity slip through the cracks!',
  manageCompaniesBlurb: 'Store company details and keep your opportunities grouped in a way that is easy to review later.',
  trackApplicationsBlurb: 'Follow each application through your hiring pipeline, from applied to offer, rejection, or closeout.',
  saveInterviewNotesBlurb: 'Capture reminders, feedback, and next steps so you can prepare better for every conversation.',
  noApplicationsFound: 'No applications found.',
} as const;